Repository ayan-biswas0412/gssoc2021-HotelOnTouch, pull requests merged in 2021-03, with the labels that each got.

#45 Footer with wave animation add #28
  hotelontouch/package.json
  hotelontouch/src/App.js
  hotelontouch/src/components/Footer.js
  hotelontouch/yarn.lock
Labels: GSSOC'21, PR:Approved

#59 added label in documentation
  README.md
Labels: GSSOC'21, PR:Approved

#60 Readme.md of hotelontouch #44
  hotelontouch/README.md
Labels: GSSOC'21, PR:Approved

#65 added gssoc logo
  README.md
Labels: GSSOC'21, PR:Approved

#78 release PR
  README.md
  backend/.gitignore
  backend/README.md
  backend/app.js
  backend/config/database.js
  backend/controller/SampleController.js
  backend/model/SampleModel.js
  backend/package.json
  backend/route/SampleRoute.js
  backend/route/index.js
  backend/yarn.lock
  hotelontouch/src/assets/logo_shreyanshi16.png
Labels: release

#40 Basic express app added
  backend/.gitignore
  backend/README.md
  backend/app.js
  backend/config/database.js
  backend/controller/SampleController.js
  backend/model/SampleModel.js
  backend/package.json
  backend/route/SampleRoute.js
  backend/route/index.js
  backend/yarn.lock
Labels: PR:Approved

#75 go to wiki addition
  README.md
Labels: GSSOC'21, PR:Approved

#77 added HotelOnTouch Logo
  hotelontouch/src/assets/logo_shreyanshi16.png
Labels: GSSOC'21, PR:Approved

#116 final PR - week 2 - merge will be 15 th march 00:00 hrs
  .github/config.yml
  README.md
  backend/.gitignore
  backend/app.js
  backend/config/swagger.js
  backend/controller/user.controller.js
  backend/model/user.model.js
  backend/package.json
  backend/route/SampleRoute.js
  backend/route/index.js
  backend/route/user.route.js
  backend/yarn.lock
  customerfrontend/App.js
  customerfrontend/android/app/build.gradle
  customerfrontend/package-lock.json
  customerfrontend/package.json
  customerfrontend/src/screens/AboutScreen.js
  customerfrontend/src/screens/HomeScreen.js
  customerfrontend/src/screens/OptionScreen.js
  customerfrontend/src/screens/ProfileScreen.js
  hotel-admin-frontend/.gitignore
  hotel-admin-frontend/public/favicon.ico
  hotel-admin-frontend/public/favicon_logo.ico
  hotel-admin-frontend/public/index.html
  hotel-restraunt-frontend/.gitignore
  hotel-restraunt-frontend/public/favicon.ico
  hotel-restraunt-frontend/public/favicon_logo.ico
  hotel-restraunt-frontend/public/index.html
  hotelontouch/.gitignore
  hotelontouch/public/favicon.ico
  hotelontouch/public/favicon_logo.ico
  hotelontouch/public/index.html
  hotelontouch/src/assets/welcome_image.svg
  hotelontouch/src/components/NavbarComponent.js
  hotelontouch/src/components/OpensourceProgramme.js
  hotelontouch/src/components/SystemFeature.js
  hotelontouch/src/pages/HomePage.js
Labels: GSSOC21, Level3, release

#79 typo in config.yml
  .github/config.yml
Labels: PR:Approved

#81 Added responsive Navbar
  hotelontouch/src/components/NavbarComponent.js
Labels: PR:Approved

#87 Added the feature section in main website
  hotelontouch/src/assets/welcome_image.svg
  hotelontouch/src/components/SystemFeature.js
  hotelontouch/src/pages/HomePage.js
Labels: PR:Approved

#97 added bottomNavigator to customerfrontend
  customerfrontend/App.js
  customerfrontend/android/app/build.gradle
  customerfrontend/package-lock.json
  customerfrontend/package.json
  customerfrontend/src/screens/AboutScreen.js
  customerfrontend/src/screens/HomeScreen.js
  customerfrontend/src/screens/OptionScreen.js
  customerfrontend/src/screens/ProfileScreen.js
Labels: GSSOC21, Level2, PR:Approved

#110 Enhance the we are part of section
  hotelontouch/src/components/OpensourceProgramme.js
Labels: GSSOC21, Level2, PR:Approved

#111 Added Contributor
  README.md
Labels: GSSOC21, Level1

#114 Added favicon to the website
  hotel-admin-frontend/.gitignore
  hotel-admin-frontend/public/favicon.ico
  hotel-admin-frontend/public/favicon_logo.ico
  hotel-admin-frontend/public/index.html
  hotel-restraunt-frontend/.gitignore
  hotel-restraunt-frontend/public/favicon.ico
  hotel-restraunt-frontend/public/favicon_logo.ico
  hotel-restraunt-frontend/public/index.html
  hotelontouch/.gitignore
  hotelontouch/public/favicon.ico
  hotelontouch/public/favicon_logo.ico
  hotelontouch/public/index.html
Labels: GSSOC21, Level1, PR:Approved

#142 Week 3 - Release PR
  backend/middlewares/user.auth.js
  backend/model/service.model.js
  hotelontouch/netlify.toml
  hotelontouch/package.json
  hotelontouch/public/index.html
  hotelontouch/src/App.css
  hotelontouch/src/App.js
  hotelontouch/src/assets/contact.svg
  hotelontouch/src/assets/logo1.svg
  hotelontouch/src/assets/logo2.svg
  hotelontouch/src/assets/logo3.svg
  hotelontouch/src/components/AdminCard.js
  hotelontouch/src/components/AllContributors.js
  hotelontouch/src/components/Contact.js
  hotelontouch/src/components/Footer.js
  hotelontouch/src/components/NavbarComponent.js
  hotelontouch/src/components/OurSolution.js
  hotelontouch/src/components/SystemFeature.js
  hotelontouch/src/components/index.js
  hotelontouch/src/index.js
  hotelontouch/src/pages/ContactPage.js
  hotelontouch/src/pages/HomePage.js
  hotelontouch/src/pages/index.js
  hotelontouch/yarn.lock
  logo/Logo(HotelOnTouch).png
Labels: GSSOC21, Level3, release

#68 logo added
  logo/Logo(HotelOnTouch).png
Labels: GSSOC21, Level2, PR:Approved

#121 Services model added
  backend/model/service.model.js
Labels: GSSOC21, Level2, PR:Approved

#126 feat: Add style to jumbotron
  hotelontouch/package.json
  hotelontouch/src/App.css
  hotelontouch/src/components/SystemFeature.js
Labels: GSSOC21, Level2, PR:Approved

#128 ADDED Dark Mode
  hotelontouch/public/index.html
  hotelontouch/src/App.js
Labels: GSSOC21, Level2, PR:Approved

#133 Middleware for user authentication added
  backend/middlewares/user.auth.js
  backend/model/service.model.js
Labels: GSSOC21, Level2, PR:Approved

#130 Tech stack
  README.md
Labels: GSSOC21, Level1, PR:Approved
